server:
  port: 8080
  servlet:
    context-path: /notification
spring:
  application:
    name: "notification-service"
  data:
    mongodb:
      uri: mongodb://mongo:27017/notification-service
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: notification-group
      # đọc message cũ nhất
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: <your_brevo_apikey>

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

info:
  app:
    name: "notification-service"
    description: "Notification Service Application"
    version: "1.0.0"

logging:
  level:
    com:
      booksn:
        notification: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"