server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
      name: "identity-service"
  datasource:
    url: jdbc:mysql://mysql:3306/identity_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

outbound:
  identity:
    client-id: "1068097809138-iespprrehar52fbuabvsahs81mtnoqtc.apps.googleusercontent.com"
    client-secret: <your-client-secret>
    redirect-uri: "http://localhost:3001/authenticate"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/

info:
  app:
    name: "identity-service"
    description: "Identity Service Application"
    version: "1.0.0"