server:
  port: 8080

app:
  api-prefix: /api

webclient:
  identity-service:
    base-url: http://identity-service:8080/identity

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://identity-service:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile-service
          uri: http://profile-service:8080
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1
        - id: post_service
          uri: http://post-service:8080
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1