server:
  port: 8888

app:
  api-prefix: /api

webclient:
  identity-service:
    base-url: http://localhost:8080/identity

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: prometheus