server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: "post-service"
  data:
    mongodb:
      uri: ${MONGODB_URI:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "post-service"
    description: "Post Service Application"
    version: "1.0.0"