server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

management:
  endpoints:
    web:
      exposure:
        include: prometheus